# NumPy: the absolute basics for beginners


## How to import NumPy

In [1]:
import numpy as np

## Array fundamentals

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a[0]

np.int64(1)

In [4]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [5]:
a[:3]

array([10,  2,  3])

In [6]:
b = a[3:]
print(b)
b[0] = 40
print(a)

[4 5 6]
[10  2  3 40  5  6]


In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
a[1, 3]

np.int64(8)

## Array attributes

In [9]:
print(a.ndim)

2


In [10]:
print(a.shape)
print(len(a.shape) == a.ndim)

(3, 4)
True


In [11]:
import math
print(a.size)
print(a.size == math.prod(a.shape))

12
True


In [12]:
print(a.dtype)

int64


## How to create a basic array

In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.ones(2)

array([1., 1.])

In [15]:
np.empty(2)

array([1., 1.])

In [16]:
np.arange(4)

array([0, 1, 2, 3])

In [17]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [18]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

## Adding, removing, and sorting elements

In [20]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## How do you know the shape and size of an array?

In [23]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]])

In [24]:
print(array_example.ndim)

3


In [25]:
print(array_example.size)

24


In [26]:
print(array_example.shape)

(3, 2, 4)


## Can you reshape an array?

In [27]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [28]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [29]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

## How to convert a 1D array into a 2D array (np.newaxis, np.expand_dims)

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

(6,)


In [31]:
a2 = a[np.newaxis, :]
print(a2.shape)

(1, 6)


In [32]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)

(1, 6)


In [33]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)

(6, 1)


In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

(6,)


In [35]:
b = np.expand_dims(a, axis=1)
print(b.shape)

(6, 1)


In [36]:
c = np.expand_dims(a, axis=0)
print(c.shape)

(1, 6)


## Indexing and slicing

In [37]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [38]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[a < 5])

[1 2 3 4]


In [39]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [40]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [41]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [42]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [43]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [44]:
list_of_coordinates = list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [45]:
print(a[b])

[1 2 3 4]


In [46]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


## How to create an array from existing data

In [47]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [48]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [49]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [50]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [51]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [52]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [53]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [54]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [55]:
b1 = a[0, :]
print(b1)
b1[0] = 99
print(b1)
print(a)

[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
b2 = a.copy()

## Basic array operations

In [57]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
print(data + ones)

[2 3]


In [58]:
print(data - ones)
print(data * data)
print(data / data)

[0 1]
[1 4]
[1. 1.]


In [59]:
a = np.array([1, 2, 3, 4])
print(a.sum())

10


In [60]:
b = np.array([[1, 1], [2, 2]])

print(b.sum(axis=0))

[3 3]


In [61]:
print(b.sum(axis=1))

[2 4]


## Broadcasting

In [62]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

## More useful array operations

In [63]:
data = np.array([1, 2, 3])
print(data.max())
print(data.min())
print(data.sum())

3
1
6


In [64]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [65]:
print(a.sum())

4.8595784


In [66]:
print(a.min())

0.05093587


In [67]:
print(a.min(axis=0))

[0.12697628 0.05093587 0.26590556 0.5510652 ]


## Creating matrices

In [68]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

2
[[3 4]
 [5 6]]
[1 3]


In [70]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [71]:
data = np.array([[1, 2], [5, 3], [4, 6]])
print(data)
print(data.max(axis=0))
print(data.max(axis=1))

[[1 2]
 [5 3]
 [4 6]]
[5 6]
[2 5 6]


In [72]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [73]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [74]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [75]:
print(np.ones(3))
print(np.zeros(3))
rng = np.random.default_rng()
print(rng.random(3))

[1. 1. 1.]
[0. 0. 0.]
[0.01909333 0.43267408 0.75936218]


In [76]:
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(rng.random((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.15182786 0.93986816]
 [0.28799278 0.35642246]
 [0.09480836 0.48399918]]


## Generating random numbers

In [77]:
rng = np.random.default_rng()
rng.integers(5, size=(2, 4))

array([[0, 2, 0, 2],
       [2, 0, 3, 3]])

## How to get unique items and counts

In [78]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [79]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [80]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [81]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [82]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [83]:
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


## Transposing and reshaping a matrix

In [84]:
data = np.array([[1, 2, 3], [4, 5, 6]])
print(data.reshape(2, 3))
print(data.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [85]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [86]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [87]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

## How to reverse an array

In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
reversed_arr = np.flip(arr)

In [90]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [91]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [92]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [93]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [94]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [95]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [96]:
arr_2d[:, 1] = np.flip(arr_2d[:, 1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


## Reshaping and flattening multidimensional arrays
`.flatten()` vs `ravel()` — 둘 다 1D로 펼치지만, ravel은 view(원본 참조)를 반환

In [97]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [98]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
a1 = x.flatten()
a1[0] = 99
print(x)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [100]:
a2 = x.ravel()
a2[0] = 98
print(x)
print(a2)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
